---
title: "Article Classification - Competition"
author: "Hippolyte GISSEROT-BOUKHLEF"
date: "November 14, 2021"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
working_directory <- ""
knitr::opts_knit$set(root.dir = working_directory)
```

```{r}
library(tm)
library(RTextTools)
library(tidytext)
library(e1071)
library (dplyr)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(kableExtra)
library(knitr)
library(caret)
```

```{r}

# Download training data
train_data <- read.csv("rcv1_db.csv", sep = ";")
train_data[train_data == ""] <- NA

# Download test data
test_data <- read.csv("competition_db.csv")

```

**First classification task (4 top-categories):**

```{r}

# Create test document-term matrix
matrix_test1 <- create_matrix(test_data$article, language = "english", removeSparseTerms = 0.99, weighting = weightTf,
                              originalMatrix = rcv.matrix.a)

# Create test container
container_test1 <- create_container(matrix_test1, labels = NULL, testSize = 1:nrow(test_data), virgin = TRUE)

# Prediction
prediction_task1 <- classify_model(container_test1, rcv.svm.c10)

```

**Second classification task (more specific categories):**

```{r}

# Create test document-term matrix
matrix_test2 <- create_matrix(test_data$article, language = "english", removeSparseTerms = 0.99, weighting = weightTf,
                                originalMatrix = rcv.matrix.b)

# Create test container
container_test2 <- create_container(matrix_test2, labels = NULL, testSize = 1:nrow(test_data), virgin = TRUE)

# Prediction
prediction_task2 <- classify_model(container_test2, rcv.svm.c10_b)

```

**Store results:**

```{r}

# Correspondence id_cat/topic_codes 
topics <- read.csv("topics.csv", sep = ";")
colnames(topics) <- c("id_cat", "topic_codes")

# Convert id_cat to topic_codes: first task
prediction1_topic_codes <- prediction_task1$SVM_LABEL
topics1 <- topics[match(as.integer(levels(prediction1_topic_codes)), topics$id_cat),]
levels(prediction1_topic_codes) <- topics1$topic_codes

# Convert id_cat to topic_codes: second task
prediction2_topic_codes <- prediction_task2$SVM_LABEL
topics2 <- topics[match(as.integer(levels(prediction2_topic_codes)), topics$id_cat),]
levels(prediction2_topic_codes) <- topics2$topic_codes

# Create data frame for task 1
id_team <- "TheUnderGolf"
classified_articles1 <- data.frame(rep(id_team, nrow(test_data)), test_data$id, str_trim(prediction1_topic_codes))
colnames(classified_articles1) <- c("id_team", "id", "cat")

# Create data frame for task 2
classified_articles2 <- data.frame(rep(id_team, nrow(test_data)), test_data$id, str_trim(prediction2_topic_codes))
colnames(classified_articles2) <- c("id_team", "id", "cat")

# Summary data frame: tasks 1 and 2
classified_articles_all <- rbind(classified_articles1, classified_articles2)
classified_articles_all <- classified_articles_all[order(classified_articles_all$id),]
write.table(classified_articles_all, file = "classified_articles.txt", sep = ",", eol = "\n", quote = F, row.names = F, 
            col.names = T)

```



